# name: Dependabot Auto Merge

# on:
#   pull_request:
#     types: [opened, synchronize]

# jobs:
#   automerge:
#     if: github.actor == 'dependabot[bot]' && contains(github.event.pull_request.title, 'security')
#     runs-on: ubuntu-latest
#     permissions:
#       contents: write
#       pull-requests: write

#     steps:
#       - name: Enable auto-merge
#         uses: peter-evans/enable-pull-request-automerge@v3
#         with:
#           merge-method: squash
